pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'echo "I am building the image in the docker"'
            }
        }
        stage('Test') {
            steps {
                sh 'echo "I am testing the image in the docker"'
            }
        }
        stage('Deploy') {
            steps {
                sh 'echo "I am development the image in the kubernetes"'
            }
        }
    }
}